// <auto-generated />
using System;
using AstroPizza.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstroPizza.Infrastructure.Migrations
{
    [DbContext(typeof(AstroPizzaDbContext))]
    [Migration("20240329175826_InitialCommit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstroPizza.Domain.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(4947),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(4992),
                            IsVegetarian = false,
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(4995),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(4996),
                            IsVegetarian = false,
                            Name = "Ham"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(4998),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(4999),
                            IsVegetarian = false,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5001),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5003),
                            IsVegetarian = false,
                            Name = "Spicy Beef"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5005),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5006),
                            IsVegetarian = false,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5008),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5009),
                            IsVegetarian = false,
                            Name = "Mexican Chicken"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5011),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5013),
                            IsVegetarian = true,
                            Name = "Peppers"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5015),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5016),
                            IsVegetarian = true,
                            Name = "Sweetcorn"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5018),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5020),
                            IsVegetarian = true,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5021),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5023),
                            IsVegetarian = true,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5025),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5026),
                            IsVegetarian = true,
                            Name = "Pineapple"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5028),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5030),
                            IsVegetarian = true,
                            Name = "Jalapenos"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5032),
                            DateLastModified = new DateTime(2024, 3, 29, 17, 58, 26, 705, DateTimeKind.Local).AddTicks(5033),
                            IsVegetarian = true,
                            Name = "Onions"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
